import 'dart:io';

import 'package:get/get_rx/src/rx_types/rx_types.dart';

import '../../../utilities/app_strings.dart';


class GeneralSettingConstant{
     RxList generalSettings = [
      {
        "title": "Show in Appointment Page",
        "section": Settings.appointment,
        "items":  [
          {"title": "Name", "label": "Name","defaultOn": true,},
          {"title": "Age Infant", "label": "AgeInfant","defaultOn": false,},
          {"title": "Age", "label": "Age","defaultOn": true,},
          {"title": "Phone", "label": "Phone","defaultOn": true,},
          {"title": "Gender", "label": "Gender","defaultOn": true,},
          {"title": "Weight", "label": "Weight","defaultOn": false,},
          {"title": "Height (Ft, Inch)", "label": "Height","defaultOn": false,},
          {"title": "Height Meter", "label": "HeightMeter","defaultOn": false,},
          {"title": "Height CM", "label": "HeightCm","defaultOn": true,},
          {"title": "Pulse", "label": "Pulse","defaultOn": true,},
          {"title": "BP", "label": "BP","defaultOn": true,},
          {"title": "Temperature Fahrenheit", "label": "Temperature","defaultOn": true,},
          {"title": "Temperature Celsius", "label": "TemperatureCelsius","defaultOn": false,},
          {"title": "Marital Status", "label": "MaritalStatus","defaultOn": true,},
          {"title": "Blood Group", "label": "BloodGroup","defaultOn": true,},
          {"title": "Drug History", "label": "MedicineTaken","defaultOn": true,},
          {"title": "OFC (Inch)", "label": "OFC","defaultOn": false,},
          {"title": "OFC (CM)", "label": "OFCcM","defaultOn": true,},
          {"title": "RR", "label": "RR","defaultOn": true,},
          {"title": "Complain", "label": "Complain","defaultOn": true,},
          {"title": "Hip (Inch)", "label": "Hip","defaultOn": false,},
          {"title": "Hip (CM)", "label": "HipCm","defaultOn": true,},
          {"title": "Waist (Inch)", "label": "Waist","defaultOn": false,},
          {"title": "Waist (CM)", "label": "WaistCm","defaultOn": true,},
          {"title": "Address", "label": "Address","defaultOn": true,},
          {"title": "Occupation", "label": "Occupation","defaultOn": true,},
          {"title": "Education", "label": "Education","defaultOn": true,},
          {"title": "Guardia Name", "label": "GuardiaName","defaultOn": true,},
          {"title": "Email", "label": "Email","defaultOn": true,},
          {"title": "Fee", "label": "Fee","defaultOn": true,},
          {"title": "DOB", "label": "DOB","defaultOn": true,},
          {"title": "Hospital Id", "label": "HospitalId","defaultOn": false,},
          {"title": "Patient Reg No", "label": "PatientRegNo","defaultOn": false,},
          {"title": "Report Patient", "label": "ReportPatient","defaultOn": true,},
        ],

      },
      {
        "title": "Show In Home Page",
        "section": Settings.settingHome,
        "items":  [
          {"title": "Chief Complaint", "label": "ChiefComplain","defaultOn": true,},
          {"title": "On Examination", "label": "OnExamination","defaultOn": true,},
          {"title": "Diagnosis", "label": "Diagnosis","defaultOn": true,},
          {"title": "Disease Activity Score", "label": "DiseaseActivity","defaultOn": true,},
          {"title": "Investigation Advice", "label": "InvestigationAdvice","defaultOn": true,},
          {"title": "Investigation Report", "label": "InvestigationReport","defaultOn": true,},
          {"title": "Investigation Report Image", "label": "InvestigationReportImage","defaultOn": false,},
          {"title": "Patient Disease Image", "label": "PatientDiseaseImage","defaultOn": false,},
          {"title": "Procedure", "label": "Procedure","defaultOn": false,},
          {"title": "History (Hx)", "label": "History","defaultOn": true,},
          {"title": "Gyne & Obs History", "label": "GyneObs","defaultOn": false,},
          {"title": "Child History", "label": "ChildHistory","defaultOn": false,},
          {"title": "Company Name Show In Brand Search", "label": "ShowCompanyName","defaultOn": false,},
          // {"title": "Default Favorite Brand Show First", "label": "DefaultFavoriteBrandShowFirst","defaultOn": true,},
          {"title": "Add brand to favorite during prescription", "label": "AddFavoriteFromPrescription","defaultOn": false,},
          {"title": "Prescription Header Footer", "label": "PrescriptionHeader","defaultOn": true,},
          {"title": "Money Receipt Print", "label": "MoneyReceipt","defaultOn": false,},
          {"title": "Referral", "label": "PatientReferral","defaultOn": false,},
          {"title": "Handout", "label": "Handout","defaultOn": true,},
          {"title": "Immunization", "label": "Immunization","defaultOn": false,},
          {"title": "Next Visit", "label": "NextVisit","defaultOn": true,},
          {"title": "Advice", "label": "Advice","defaultOn": true,},
          {"title": "Certificate", "label": "Certificate","defaultOn": false,},
          {"title": "Rx Icon", "label": "RxIcon","defaultOn": false,},
          {"title": "Name", "label": "Name","defaultOn": true,},
          {"title": "Age Infant", "label": "AgeInfant","defaultOn": false,},
          {"title": "Age", "label": "Age","defaultOn": true,},
          {"title": "Phone", "label": "Phone","defaultOn": false,},
          {"title": "Gender", "label": "Gender","defaultOn": true,},
          {"title": "Weight", "label": "Weight","defaultOn": false,},
          {"title": "Pulse", "label": "Pulse","defaultOn": true,},
          {"title": "Temperature Fahrenheit", "label": "Temperature","defaultOn": true,},
          {"title": "BP", "label": "BP","defaultOn": true,},
          {"title": "Temperature Celsius", "label": "TemperatureCelsius","defaultOn": false,},
          {"title": "Height (Ft, Inch)", "label": "Height","defaultOn": false,},
          {"title": "Height Meter", "label": "HeightMeter","defaultOn": false,},
          {"title": "Height CM", "label": "HeightCm","defaultOn": false,},
          {"title": "Enable Login Button (For Developer)", "label": "EnableLogin","defaultOn": false,},
          {"title": "Marital Status", "label": "MaritalStatus","defaultOn": false,},
          {"title": "Blood Group", "label": "BloodGroup","defaultOn": false,},
          {"title": "Drug History", "label": "MedicineTaken","defaultOn": false,},
          {"title": "OFC (Inch)", "label": "OFC","defaultOn": false,},
          {"title": "OFC (CM)", "label": "OFCcM","defaultOn": false,},
          {"title": "RR", "label": "RR","defaultOn": false,},
          {"title": "Complain", "label": "Complain","defaultOn": false,},
          {"title": "Hip (Inch)", "label": "Hip","defaultOn": false,},
          {"title": "Hip (CM)", "label": "HipCm","defaultOn": false,},
          {"title": "Waist (Inch)", "label": "Waist","defaultOn": false,},
          {"title": "Waist (CM)", "label": "WaistCm","defaultOn": false,},
          {"title": "Address", "label": "Address","defaultOn": false,},
          {"title": "Occupation", "label": "Occupation","defaultOn": false,},
          {"title": "Education", "label": "Education","defaultOn": false,},
          {"title": "Guardia Name", "label": "GuardiaName","defaultOn": false,},
          {"title": "Email", "label": "Email","defaultOn": false,},
          {"title": "Fee", "label": "Fee","defaultOn": false,},
          {"title": "Date", "label": "Date","defaultOn": false,},
          {"title": "Report Patient", "label": "ReportPatient","defaultOn": false,},
          {"title": "Hospital Id", "label": "HospitalId","defaultOn": false,},
          {"title": "Patient Reg No", "label": "PatientRegNo","defaultOn": false,},
          {"title": "Serial", "label": "Serial","defaultOn": false,},
          {"title": "Prescription Link SMS", "label": "SentPrescriptionSms","defaultOn": false,},
          {"title": "Prescription Link Email", "label": "SentPrescriptionEmail","defaultOn": false,},
          {"title": "Physician Notes", "label": "PhysicianNotes","defaultOn": false,},
          {"title": "Treatment Plan", "label": "TreatmentPlan","defaultOn": false,},
          {"title": "Referral Short", "label": "ReferralShort","defaultOn": false,},
          // {"title": "Enable End Drawer Medicine Add", "label": "EndDrawerMedicineAdd","defaultOn": false,},
          // {"title": "Enable End Drawer for Clinical Data", "label": "EndDrawerClinicalData","defaultOn": false,},
          {"title": "Enable Text Writing box for Clinical Data", "label": "EnableTextWritingBox","defaultOn": false,},
          {"title": "Enable recent uses Investigation advice in home", "label": "EnableRecentInvAdvHome","defaultOn": false,},
          {"title": "Selected Drug - Edit in Input Field", "label": "EnableDrugEditHome","defaultOn": false,},
          {"title": "Drug Search in Home", "label": "EnableDrugSearchHome","defaultOn": Platform.isAndroid ? false : true,},
          {"title": "Clinical Data Ordering", "label": "ClinicalDataOrder","defaultOn": false,},
          {"title": "Selected Drug - Dose Short Form ", "label": "DoseShortForm","defaultOn": false,},
          {"title": "Selected Drug - Generic Name Show ", "label": "GenericShowInHome","defaultOn": true,},
          {"title": "Selected Drug - Company Name Show ", "label": "CompanyNameShowSelectedDrug","defaultOn": true,},
          {"title": "Selected Drug - Drug Default Dose Create Button ", "label": "DrugDefaultDoseButton","defaultOn": true,},
          {"title": "Selected Drug - Drug Delete Button ", "label": "DeleteButton","defaultOn": true,},
          {"title": "Selected Drug - Alter Company Button ", "label": "AlterCompanyButton","defaultOn": true,},
          {"title": "Selected Drug - Alter Brand Same Generic ", "label": "AlterBrandButton","defaultOn": true,},
          {"title": "Selected Drug - Note Button ", "label": "NoteButton","defaultOn": true,},
          // {"title": "Eye Specialist (Glass Recommendation)", "label": "GlassRecommendation","defaultOn": false,},
          // {"title": "Eye Specialist (GP Print)", "label": "GlassRecommendationPrint","defaultOn": false,},


        ],
      },

      {
        "title": "Show in Prescription Print Page",
        "section": "PrescriptionPrintPage",
        "items":  [
          {"title": "Chief Complaint", "label": "chiefComplain","defaultOn": true,},
          {"title": "On Examination", "label": "Examination","defaultOn": true,},
          {"title": "Diagnosis", "label": "Diagnosis","defaultOn": true,},
          {"title": "Disease Activity Score", "label": "DiseaseActivity","defaultOn": true,},
          {"title": "Investigation Advice", "label": "InvestigationAdvice","defaultOn": true,},
          {"title": "Investigation Report", "label": "InvestigationReport","defaultOn": true,},
          {"title": "Procedure", "label": "Procedure","defaultOn": true,},
          {"title": "Gyne & Obs History", "label": "GyneObs","defaultOn": false,},
          {"title": "Child History", "label": "ChildHistory","defaultOn": false,},
          {"title": "History (others)", "label": "History","defaultOn": false,},

          // {"title": "Prescription Header Footer", "label": "PrescriptionHeaderFooter","defaultOn": true,},
          {"title": "Immunization", "label": "Immunization","defaultOn": false,},
          {"title": "Next Visit", "label": "NextVisit","defaultOn": true,},
          {"title": "Advice", "label": "Advice","defaultOn": true,},
          {"title": "Horizontal Border (Below Patient Info)", "label": "horizontalBorder","defaultOn": true,},
          {"title": "Vertical Border Show", "label": "verticalBorder","defaultOn": true,},
          {"title": "Rx Icon", "label": "RxIcon","defaultOn": true,},
          {"title": "Brand & doses format uppercase", "label": "BrandDosesUppercase","defaultOn": false,},
          {"title": "Name label show", "label": "NameLabel","defaultOn": true,},
          {"title": "Name show", "label": "Name","defaultOn": true,},
          {"title": "Patient ID label show", "label": "PatientIdLabel","defaultOn": true,},
          {"title": "Patient ID show", "label": "PatientId","defaultOn": true,},
          {"title": "Age label show", "label": "AgeLabel","defaultOn": true,},
          {"title": "Age show", "label": "Age","defaultOn": true,},
          {"title": "Age Printing format (30Y)", "label": "AgeYear","defaultOn": true,},
          {"title": "Age Printing format (30Y-3M)", "label": "AgeYearMon","defaultOn": false,},
          {"title": "Age Printing format (30Y-20M-5D)", "label": "AgeYearMonthDay","defaultOn": false,},
          {"title": "Age Printing format (30Y-20M-5D-10H-30Min)", "label": "AgeYearMonthDayMin","defaultOn": false,},
          {"title": "Gender label show", "label": "GenderLabel","defaultOn": true,},
          {"title": "Gender show", "label": "Gender","defaultOn": true,},
          {"title": "Date label show", "label": "DateLabel","defaultOn": true,},
          {"title": "Date show", "label": "Date","defaultOn": true,},
          {"title": "Temperature Celsius", "label": "TemperatureCelsius","defaultOn": false,},
          {"title": "Clinical card transparent color", "label": "clinicalCardColor","defaultOn": true,},
          {"title": "OFC (Inch)", "label": "OFC","defaultOn": false,},
          {"title": "Hip (Inch)", "label": "Hip","defaultOn": false,},
          {"title": "Height (Ft, Inch)", "label": "Height","defaultOn": false,},
          {"title": "Height Meter", "label": "HeightMeter","defaultOn": false,},
          {"title": "Hip (Inch)", "label": "Hip","defaultOn": false,},
          {"title": "Waist (Inch)", "label": "Waist","defaultOn": false,},
          {"title": "Signature Analog ", "label": "AnalogSignature","defaultOn": false,},
          {"title": "Signature Digital ", "label": "DigitalSignature","defaultOn": false,},
          {"title": "Patient All Info disable ", "label": "offPatientAllInfo","defaultOn": false,},
          {"title": "QR Code", "label": "QRCode","defaultOn": false,},
          {"title": "Physician Notes", "label": "PhysicianNotes","defaultOn": false,},
          {"title": "Treatment Plan", "label": "TreatmentPlan","defaultOn": false,},
          {"title": "Referral Short", "label": "ReferralShort","defaultOn": false,},
          {"title": "Advice title print in Bnagla", "label": "AdviceTitleBangla","defaultOn": true,},
          {"title": "Horizontal Border (Above Patient Info)", "label": "HorizontalBorderTop","defaultOn": true,},
        ],
      },
      {
        "title": "Assistant Access",
        "section": Settings.assistantAccess,
        "items":  [
          {"title": "Create Appointment", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Clinical Data Insert Option", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription List View", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Print", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Email & SMS", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Template Option", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Money Receipt", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Followup List View", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Handout access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Referral Access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Report", "label": "LiveDataSync","defaultOn": false,},
        ],
      },
       {
        "title": "Assistant Doctor Access",
        "section": Settings.assistantDoctorAccess,
        "items":  [
          {"title": "Create Appointment", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Clinical Data Insert Option", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription List View", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Print", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Email & SMS", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Template Create", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Edit", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Medical Certificate Access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Dashboard view", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Clinical Permanent Data Insert Option", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Edit Access (Only clinical data can change)", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Drug Insert Access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Money Receipt", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Followup List View", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Handout access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Referral Access", "label": "LiveDataSync","defaultOn": false,},
          {"title": "Prescription Report", "label": "LiveDataSync","defaultOn": false,},
        ],
      },
       {
        "title": "Others",
        "section": Settings.others,
        "items":  [
          {"title": "Live Data upload and download (Rx, Appointment, Patient)", "label": Settings.LiveDataSync,"defaultOn": false,},
          {"title": "Prescription Email & SMS from Rx List", "label": "LiveDataSync","defaultOn": false,},

        ],
      },

    ].obs;

    orderBy(){
      for(var setting in generalSettings) {
        List items = setting["items"];
        items.sort((a, b) => a["title"].compareTo(b["title"]));
      }
    }

}
